const productFamilies = [
  {
    id: 'oled', kicker: '01_OLED', title: 'OLED / OLED evo', pill: 'Premium Black',
    description: 'Nero perfetto, contrasto infinito, Dolby Vision e gaming premium. La gamma più alta per cinema, design e performance.',
    familyClass: 'oled-family',
    products: [
      { id:'oledT', className:'oled-card ultra', eyebrow:'Signature', tag:'Ultra Premium', name:'OLED T Signature', short:'Soluzione iconica di top gamma per massimo impatto e posizionamento premium.', chips:['Flagship','OLED','Design Hero'], label:'OLED SIGNATURE', intro:'Soluzione iconica e ultra premium della gamma OLED, pensata per massimo impatto, design e posizionamento top.', selling:'Da proporre al cliente top spender che cerca una soluzione esclusiva, scenografica e distintiva.', specs:[['Tecnologia','OLED Signature'],['Target','Ultra premium / design hero'],['Punti forza','Nero perfetto, design iconico, esperienza flagship'],['Cliente ideale','Design lover, top spender, early adopter']] },
      { id:'oledB6', className:'oled-card', eyebrow:'Serie B', tag:'Entry OLED', name:'OLED B6E', short:'La porta d’ingresso OLED: Perfect Black, Dolby Vision / Atmos, α8 Gen3 e gaming 4K 120Hz.', chips:['83” 77” 65” 55” 48” 42”','α8 Gen3','120Hz'], label:'OLED ENTRY', intro:'La porta d’ingresso al mondo OLED LG: Perfect Black, Dolby Vision, Dolby Atmos, α8 Gen3 e gaming 4K 120Hz.', selling:'Perfetto per chi vuole entrare nel mondo OLED senza arrivare alle serie più costose. Punta su nero perfetto, contrasto e qualità cinema.', specs:[['Polliciaggi','83” / 77” / 65” / 55” / 48” / 42”'],['Processore','α8 Gen3 con AI'],['Gaming','4K 120Hz, VRR, G-Sync, FreeSync'],['Audio / Video','Dolby Vision e Dolby Atmos']] },
      { id:'oledC6', className:'oled-card best', eyebrow:'Serie C', tag:'Best Seller', name:'OLED C64 / C65 / C66', short:'OLED evo best seller con α11 Gen3, Hyper Radiant Color, Dolby Vision / Atmos e gaming 165Hz.', chips:['83” 77” 65” 55” 48” 42”','α11 Gen3','165Hz'], label:'OLED BEST SELLER', intro:'OLED evo best seller con α11 Gen3, Hyper Radiant Color, colori certificati Perfect Color e gaming 4K 165Hz.', selling:'È il modello da proporre quando il cliente cerca il miglior equilibrio tra prestazioni premium, cinema, gaming e prezzo percepito.', specs:[['Polliciaggi','83” / 77” / 65” / 55” / 48” / 42”'],['Processore','α11 Gen3 AI'],['Luminosità','Hyper Radiant Color / Brightness Booster Pro'],['Gaming','4K 165Hz, ClearMR 10000']] },
      { id:'oledG6', className:'oled-card wall', eyebrow:'Serie G', tag:'Gallery', name:'OLED G6 Wall', short:'Top OLED evo con Reflection Free Premium, Hyper Radiant x3.9, audio 4.2 60W e staffa filo muro.', chips:['97” 83” 77” 65” 55”','5 anni pannello','165Hz'], label:'OLED GALLERY', intro:'Top OLED evo con Hyper Radiant x3.9, Reflection Free Premium, audio 4.2 60W, gaming 165Hz e staffa filo muro.', selling:'Da proporre al cliente premium che vuole il massimo della qualità immagine e un TV integrato in modo elegante nell’ambiente.', specs:[['Polliciaggi','97” / 83” / 77” / 65” / 55”'],['Processore','α11 Gen3 con AI'],['Design','One Wall / staffa Zero-Gap'],['Garanzia','5 anni garanzia pannello OLED']] },
      { id:'oledG6S', className:'oled-card wall', eyebrow:'Serie G', tag:'Stand', name:'OLED G6S', short:'Versione con base centrale per cliente premium che cerca massima qualità OLED e installazione d’appoggio.', chips:['77” 65” 55” 48”','α11 Gen3','Dolby Vision'], label:'OLED GALLERY STAND', intro:'Versione con base centrale della serie G, pensata per chi cerca qualità top gamma OLED senza installazione a parete.', selling:'Ideale per cliente top spender che non può o non vuole appendere il TV ma vuole comunque il massimo OLED evo.', specs:[['Polliciaggi','77” / 65” / 55” / 48”'],['Processore','α11 Gen3 con AI'],['Video','Dolby Vision, Hyper Radiant, Reflection Free su tagli compatibili'],['Gaming','165Hz, VRR, G-Sync, FreeSync']] }
    ]
  },
  {
    id:'mrgb', kicker:'02_MRGB', title:'Micro RGB / Mini RGB', pill:'Color Innovation', description:'Nuova frontiera colore sui TV LED: RGB Primary Color, certificazioni TriColor / DualColor e gaming evoluto.', familyClass:'mrgb-family',
    products:[
      { id:'mrgb96', className:'mrgb-card hero', eyebrow:'Micro RGB', tag:'Flagship LED', name:'MRGB96', short:'Micro RGB evo AI 96 con α11 Gen3, TriColor 100%, Micro Dimming Ultra, fino a 4000 nit e gaming 165Hz.', chips:['100” 86” 75”','α11 Gen3','Motion Booster 330'], label:'MICRO RGB FLAGSHIP', intro:'La nuova frontiera dei TV LED: RGB Primary Color Ultra, certificazione TriColor 100%, Micro Dimming Ultra e α11 Gen3.', selling:'Da usare come hero LED premium: colori mai visti su LED, luminosità altissima e performance gaming top.', specs:[['Tecnologia','Micro RGB'],['Colore','100% BT.2020, DCI-P3, Adobe RGB'],['Processore','α11 AI 4K Gen3'],['Gaming','165Hz con Motion Booster 330']] },
      { id:'mrgb88', className:'mrgb-card pro', eyebrow:'Mini RGB', tag:'Pro', name:'MRGB88B', short:'Mini RGB evo AI Pro con DualColor 100%, α8 Gen3, Precision HDR Master Pro, Dolby Vision / Atmos e 144Hz.', chips:['86” 75” 65” 55” 50”','DualColor 100%','HDR Master Pro'], label:'MINI RGB PRO', intro:'Mini RGB premium con RGB Primary Color Pro, DualColor 100%, α8 Gen3 e Precision HDR Master Pro.', selling:'È il modello Mini RGB da proporre quando vuoi salire rispetto al QNED e valorizzare colore, HDR e gaming.', specs:[['Polliciaggi','86” / 75” / 65” / 55” / 50”'],['Colore','100% DCI-P3 e Adobe RGB'],['HDR','Precision HDR Master Pro'],['Gaming','144Hz, Dolby Vision Gaming']] },
      { id:'mrgb87', className:'mrgb-card', eyebrow:'Mini RGB', tag:'Core', name:'MRGB87B', short:'Mini RGB evo AI con RGB Primary Color Pro, Precision Dimming, α8 Gen3, Dolby Vision / Atmos e gaming 144Hz.', chips:['86” 75” 65” 55” 50”','α8 Gen3','Precision Dimming'], label:'MINI RGB', intro:'Mini RGB con DualColor 100%, α8 Gen3, Precision Dimming, Dolby Vision / Atmos e gaming 144Hz.', selling:'Perfetto per raccontare l’evoluzione del MiniLED con colori più autentici e saturi.', specs:[['Polliciaggi','86” / 75” / 65” / 55” / 50”'],['Tecnologia','Mini RGB'],['Dimming','Precision Dimming'],['Processore','α8 AI 4K Gen3']] }
    ]
  },
  {
    id:'qned', kicker:'03_QNED', title:'QNED Mini LED', pill:'MiniLED Lineup', description:'Tutta la gamma QNED 2026 è MiniLED: più contrasto, più colore e grande varietà di polliciaggi.', familyClass:'qned-family',
    products:[
      { id:'qned93', className:'qned-card hero', eyebrow:'Top QNED', tag:'Big Screen', name:'QNED93B', short:'QNED evo AI Mini LED fino a 115”, α8 Gen3, Dynamic QNED Color Pro, Precision Dimming Ultra e audio 2.2 40W.', chips:['115” 85” 75” 65” 55”','Dolby Vision','165Hz gaming'], label:'QNED TOP', intro:'Il QNED big screen fino a 115”: Dynamic QNED Color Pro, Precision Dimming Ultra, α8 Gen3, Dolby Vision e Atmos.', selling:'Da proporre al cliente che vuole grande formato, forte impatto visivo e qualità MiniLED premium.', specs:[['Polliciaggi','115” / 85” / 75” / 65” / 55”'],['Dimming','Precision Dimming Ultra'],['Processore','α8 AI 4K Gen3'],['Audio','2.2 canali, 40W, Dolby Atmos']] },
      { id:'qned87', className:'qned-card', eyebrow:'Premium', tag:'Ultra Slim', name:'QNED87B', short:'QNED evo MiniLED fino a 100”, Dynamic QNED Color Pro, α8 Gen3, Precision Dimming e design super slim.', chips:['100” 86” 75” 65” 55” 50” 43”','144Hz','Dolby Vision'], label:'QNED PREMIUM', intro:'QNED evo MiniLED fino a 100”, Dynamic QNED Color Pro, α8 Gen3, Dolby Vision e design super slim.', selling:'Ottimo per cliente che cerca un MiniLED premium, sottile e versatile, con tagli molto ampi.', specs:[['Polliciaggi','100” / 86” / 75” / 65” / 55” / 50” / 43”'],['Dimming','Precision Dimming'],['Gaming','144Hz, Motion Booster 288'],['Design','Super Slim Design']] },
      { id:'qned86', className:'qned-card', eyebrow:'Premium', tag:'Super Slim', name:'QNED86B', short:'MiniLED con 100% Volume Colore, α8 Gen3, Dolby Vision e profilo sottile da 29,7 mm.', chips:['86” 75” 65” 55” 50” 43”','α8 Gen3','144Hz'], label:'QNED PREMIUM', intro:'MiniLED con Dynamic QNED Color Pro, α8 Gen3, Dolby Vision e profilo super sottile da 29,7 mm.', selling:'Da proporre a chi cerca immagine, design e gaming in un prodotto premium ma accessibile rispetto ai top gamma.', specs:[['Polliciaggi','86” / 75” / 65” / 55” / 50” / 43”'],['Colore','100% Volume Colore'],['Processore','α8 Gen3'],['Design','29,7 mm sui tagli indicati']] },
      { id:'qned80', className:'qned-card entry', eyebrow:'Mid', tag:'QNED evo', name:'QNED80B', short:'QNED evo MiniLED con Dynamic QNED Color Pro, AI Hub, FILMMAKER Mode e gaming VRR 60fps.', chips:['85” 75” 65” 55” 50” 43”','α7 Gen9','60Hz'], label:'QNED MID', intro:'QNED evo con Dynamic QNED Color Pro, MiniLED, AI Hub, FILMMAKER Mode e gaming evoluto VRR 60fps.', selling:'Ideale per cliente famiglia che vuole più qualità colore e smart experience rispetto a un LED tradizionale.', specs:[['Polliciaggi','85” / 75” / 65” / 55” / 50” / 43”'],['Processore','α7 AI 4K Gen9'],['Refresh','60Hz'],['Smart','webOS 26 con Multi AI']] },
      { id:'qned70', className:'qned-card entry', eyebrow:'Entry', tag:'QNED AI', name:'QNED70B', short:'Porta d’ingresso QNED: Dynamic QNED Color, MiniLED, webOS con Multi AI e design Linear Flow.', chips:['85” 75” 65” 55” 50” 43”','α7 Gen9','AI Magic Remote'], label:'QNED ENTRY', intro:'Porta d’ingresso QNED con Dynamic QNED Color, MiniLED, AI Hub, Magic Remote e design Linear Flow.', selling:'Da proporre a chi vuole fare un salto rispetto al 4K tradizionale mantenendo un prezzo accessibile.', specs:[['Polliciaggi','85” / 75” / 65” / 55” / 50” / 43”'],['Colore','Dynamic QNED Color'],['Processore','α7 AI 4K Gen9'],['Design','Linear Flow']] }
    ]
  },
  {
    id:'nano', kicker:'04_Nano4KUHD', title:'NANO 4K UHD', pill:'Value Smart TV', description:'La gamma smart 4K più accessibile, con AI, webOS, Nano Detail Enhancer e argomenti valore per fascia entry.', familyClass:'nano-family',
    products:[
      { id:'nu90_98', className:'nano-card hero', eyebrow:'Ultra Large', tag:'98”', name:'NU90 98”', short:'TV 4K ultra large con α8 Gen3, Nano Detail Enhancer, 144Hz, Motion Booster 288 e AI Magic Remote.', chips:['98”','α8 Gen3','4 HDMI 2.1'], label:'NANO ULTRA LARGE', intro:'TV 4K ultra large da 98” con α8 Gen3, Nano Detail Enhancer, AI Magic Remote e gaming fino a 144fps.', selling:'Da proporre al cliente che vuole effetto cinema a casa con grandissimo polliciaggio e performance superiori ai comuni 4K.', specs:[['Polliciaggio','98”'],['Processore','α8 Gen3 con AI'],['Gaming','4K 144fps / 1080p 288fps'],['Connettività','4 HDMI 2.1']] },
      { id:'nu90', className:'nano-card', eyebrow:'Nano', tag:'Premium 4K', name:'NU90', short:'Nano 4K UHD con Nano Detail Enhancer, AI Hub, Magic Remote, FILMMAKER Mode e gaming evoluto.', chips:['85” 75” 65” 55” 50” 43”','α7 Gen9','20W'], label:'NANO PREMIUM', intro:'Nano 4K UHD con Nano Detail Enhancer, AI Hub, Magic Remote, FILMMAKER Mode e gaming evoluto.', selling:'Perfetto per cliente che cerca una smart TV 4K evoluta con funzioni AI e telecomando puntatore.', specs:[['Polliciaggi','85” / 75” / 65” / 55” / 50” / 43”'],['Tecnologia','Nano Detail Enhancer'],['Processore','α7 AI 4K Gen9'],['Audio','2.0 canali 20W']] },
      { id:'nu85', className:'nano-card', eyebrow:'Nano', tag:'Smart Value', name:'NU85', short:'Smart TV 4K con Nano Detail Enhancer, webOS con Multi AI, Design Linear Flow e aggiornamenti garantiti.', chips:['85” 75” 65” 55” 50” 43”','HDR10 Pro','60Hz'], label:'NANO SMART VALUE', intro:'Smart TV 4K con Nano Detail Enhancer, webOS con Multi AI, Design Linear Flow e aggiornamenti garantiti.', selling:'Da proporre come smart TV completa per chi vuole valore, AI e design senza salire troppo di fascia.', specs:[['Polliciaggi','85” / 75” / 65” / 55” / 50” / 43”'],['Video','HDR10 Pro, FILMMAKER Mode'],['Smart','webOS con Multi AI'],['Refresh','60Hz']] },
      { id:'nu80', className:'nano-card entry', eyebrow:'Nano', tag:'Entry', name:'NU80', short:'4K accessibile con Nano Detail Enhancer, FILMMAKER Mode, Game Optimizer, LG Channels e Sports Portal.', chips:['85” 75” 65” 55” 50” 43”','VRR 60fps','webOS'], label:'NANO ENTRY', intro:'4K accessibile con Nano Detail Enhancer, FILMMAKER Mode, Game Optimizer, LG Channels e Sports Portal.', selling:'Ideale per primo prezzo evoluto: più valore, più contenuti e smart experience completa.', specs:[['Polliciaggi','85” / 75” / 65” / 55” / 50” / 43”'],['Smart','LG Channels e Sports Portal'],['Gaming','VRR fino a 60fps'],['Aggiornamenti','webOS Re:New 4 aggiornamenti in 5 anni']] }
    ]
  }
];
